import type { AllyDesignation, Designation } from "./rules";

/** Builder copy, taken from the design (Catalogue.dc.html and Catalogue - Wide.dc.html). */
export const t = {
  faction: "Faction",
  gameSize: "Game size",
  allegiance: "Allegiance",
  listName: "List name",
  untitled: "Untitled list",
  save: "Save",
  saving: "Saving…",
  saved: "Saved",
  back: "My lists",
  leaveUnsaved: "Leave without saving? Your changes to this list will be lost.",
  assetEffectHead: "Effect",
  assetTargetHead: "Legal target",
  assetAdd: "Add to force",
  assignHead: "Attach to",
  assignNone: "No unit in your force can take this asset yet.",
  uniqueTaken: "Unique — only one per Force",
  assetTakenShort: "Already in your force",
  assetTaken: "An Asset may be purchased only once per Force. Remove it from your force to attach it elsewhere.",
  forceAssetsHead: "Force assets",
  duplicate: "Duplicate",
  assetNoText: "No rules text for this asset in the extracted data yet.",
  nav: { catalogue: "Catalogue", force: "Force", status: "Status" },
  deployment: "Deployment points",
  support: "Support points",
  clearFilters: "Clear",
  resetForce: "Clear force",
  searchPh: "Search units, types, abilities",
  tabs: { units: "Units", allies: "Allies", assets: "Assets" },
  desig: { trooper: "Trooper", leader: "Leader", specialist: "Specialist", support: "Support", unique: "Unique" } as Record<Designation, string>,
  allyDesig: { advisor: "Advisor", seconding: "Seconding", dark_cult: "Dark Cult" } as Record<AllyDesignation, string>,
  sizes: { learning: "learning", small: "small", standard: "standard", large: "large" } as Record<string, string>,
  ccHead: "CC",
  shortHead: "Short",
  longHead: "Long",
  abilities: "Special abilities",
  attached: "Attached",
  addToForce: "Add to force",
  remove: "Remove",
  close: "Close",
  allyOk: (d: string, src: string) => `${d} — ${src} ally, legal for this force`,
  assetOk: (n: number, req: string) => `${n} ${n === 1 ? "eligible unit" : "eligible units"} — needs ${req}`,
  assetNone: (req: string) => `No eligible unit — needs ${req}`,
  assetForce: "Applies to the force, no target needed",
  emptyTitle: "Nothing matches",
  emptyBody: "Search covers unit names, unit types, designations and ability names.",
  rosterEmptyTitle: "Force is empty",
  rosterEmptyBodyMobile: "Switch to Catalogue and tap + on any unit. It appears here as its full printed profile.",
  rosterEmptyBody: "Add units from the catalogue on the left. Each one appears here as its full printed profile, so the force reads as a stack of cards rather than a list of names.",
  catalogueLine: (n: number) => `${n} entries`,
  rosterLine: (n: number, dp: number, lim: number) => `${n} units · ${dp}/${lim} DP`,
  legal: "Legal",
  illegal: "Not legal yet",
  legalEmpty: "Add units to begin. The rulebook requires at least one Leader.",
  legalOk: "Every requirement in the rulebook is satisfied. This force is ready to play.",
  legalBad: (n: number) => (n === 1 ? "1 issue must be resolved before this force is legal." : `${n} issues must be resolved before this force is legal.`),
  issues: "Issues",
  noIssues: "No issues — force is legal",
  nothingToCheck: "Nothing to check yet — the force is empty",
  composition: "Composition",
  comp: { units: "Units in force", types: "Unit types", leaders: "Leaders", support: "Support units", allies: "Ally DP", assets: "Faction assets" },
  abilityPending: "Rules text for this ability is not in the extracted bundle yet — the key and its parameters are shown above.",
  traitPending: "Rules text for this Weapon Trait is not in the extracted bundle yet — the key and its parameters are shown above.",
  export: "Export",
  exportPdf: "Printable force sheet",
  exportTxt: "Plain text list",
  exportJson: "Force data file",
  dpNote: (left: number, lim: number) => (left >= 0 ? `${left} DP remaining of ${lim}` : `${Math.abs(left)} DP over the limit`),
  spNote: (spent: number, avail: number) => `${spent} spent of ${avail} available`,
};
